### ISSUE TITLE
'ImportError: cannot import name forms' in aldryn_config.py on local installation

### ISSUE THREAD

**Issue by macolo** [aldryn/aldryn-events#214]
If I check out aldryn-events into addons-dev and then run `aldryn addon validate` or rebuild the `web` container I get 

```
Error: Traceback (most recent call last):
  File "aldryn_client/validators/addon.py", line 33, in validate_aldryn_config_py
  File "/var/folders/11/0xv_krj10k10mlxrx2sdstc00000gn/T/tmp_aldryn_client_3Lll5F/aldryn_config.py", line 1, in <module>
    from aldryn_client import forms
ImportError: cannot import name forms
```

**Comment by macolo** [comment]
seems to be resolved or unrelated.
