### ISSUE TITLE
Unable to migrate aldryn in my pc

### ISSUE THREAD

**Issue by krishnapbmmk** [aldryn/aldryn-events#254]
please help regrading this issue and below in mention what kind error i getting 

(env) PS C:\Users\ZeroZilla\Desktop\zdc> ./manage.py migrate
Traceback (most recent call last):
  File "C:\Users\ZeroZilla\Desktop\zdc\manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\ZeroZilla\Desktop\env\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\ZeroZilla\Desktop\env\lib\site-packages\django\core\management\__init__.py", line 338, in execute
    django.setup()
  File "C:\Users\ZeroZilla\Desktop\env\lib\site-packages\django\__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\ZeroZilla\Desktop\env\lib\site-packages\django\apps\registry.py", line 89, in populate
    "duplicates: %s" % app_config.label)
django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: djangocms_text_ckeditor
(env) PS C:\Users\ZeroZilla\Desktop\zdc>

i 'm unable to access aldryn plagins

**Comment by juanj** [comment]
Is possible that you have `djangocms_text_ckeditor `dublicated in the django config file on `INSTALLED_APPS`
